on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      who-to-greet-env: 'Felipe'
    steps:
      - name: Hello world action step
        id: api
        uses: gitahernandezorg/my-docker-action-fhernandez@v23
        with:
          who-to-greet: 'Mona the Octocat'
          github_token: ${{ secrets.OWN_GITHUB_TOKEN }}
      # Use the output from the `hello`
      - name: Get the output time
        run: echo "Example ${{ steps.api.outputs.test_variable }}"