on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      who-to-greet-env: ${{ secrets.OWN_GITHUB_TOKEN }}
    steps:
      - name: Hello world action step
        id: api
        uses: gitahernandezorg/my-docker-action-fhernandez@v30
        with:
          who-to-greet: 'Mona the Octocat'
          github_token: ${{ secrets.OWN_GITHUB_TOKEN }}

      - name: Print test_variable
        run: echo "${{ steps.api.outputs.test_variable }}"

      - name: Print Cretaed secret
        run: echo "${{ secrets.MY_SECRET_7166CFB7E42F415F9063D96C3C3FFF9F }}"
