on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    permissions:
      actions: read
      pull-requests: write
    steps:
      - name: Hello world action step
        id: hello
        uses: gitahernandezorg/my-docker-action-fhernandez@v20
        with:
          who-to-greet: 'Mona the Octocat'
          github_token: "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"
      # Use the output from the `hello` step f
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"