on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      who-to-greet-env: ${{ secrets.OWN_GITHUB_TOKEN }}
    steps:
      - name: Hello world action step
        id: api
        uses: gitahernandezorg/my-docker-action-fhernandez@v30
        with:
          who-to-greet: 'Mona the Octocat'
          github_token: ${{ secrets.OWN_GITHUB_TOKEN }}

      - name: Print test_variable
        run: echo "${{ steps.api.outputs.test_variable }}"

      - name: Print Multiline
        run: echo "${{ steps.api.outputs.multiline }}"

      - name: Print Org Secret
        run: echo "${{ secrets.my_secret_bad9d506a8134da3bd29910c48750901_ORG }}"

      - name: Print Env Secret
        run: echo "${{ secrets.my_secret_bad9d506a8134da3bd29910c48750901_ENV }}"

      - name: Print Repo Secret
        run: echo "${{ secrets.my_secret_bad9d506a8134da3bd29910c48750901_REPO }}"