on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: gitahernandezorg/my-docker-action-fhernandez@v20
        with:
          who-to-greet: 'Mona the Octocat'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step f
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"